server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      auto-fill-strategy:
        enable: true

  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.notebook.note_back.model

logging:
  level:
    com:
      note:
        mapper: debug
        service: info
        controller: info

note:
  share: ${NOTE_SHARE:https://localhost:8080/note/viewSharedNote/}
#note:
#  jwt:
#    # ??jwt??????????
#    admin-secret-key: note
#    # ??jwt????
#    admin-ttl: 7200000
#    # ?????????????
#    admin-token-name: token
#  alioss:
#    # ?????oss?endpoint
#    endpoint:
#    # ?????oss?accessKeyId
#    access-key-id:
#    # ?????oss?accessKeySecret
#    access-key-secret:
#    # ?????oss?bucket??
#    bucket-name: